from tkinter import *
import tkinter.messagebox as msgbox
import base64,os

img=b'AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAEAAAJAQAQCQEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMGMzMzcDMzM4QzMzNtMzMzaTMzM2czMzNXMzMzRDMzMz8zMzM+MzMzMjMzMyIzMzMWMzMzDDMzMwkzMzMJMzMzBTMzMwEzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzATMzMwUzMzMIMzMzCTMzMwwzMzMVMzMzITMzMzEzMzM+MzMzPzMzM0QzMzNWMzMzZjMzM2kzMzNtMzMzgzMzM3MzMzMIMzMzAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzITMzM9wzMzP/MzMz/zMzM/8zMzP/MzMz/DMzM/czMzP2MzMz9TMzM+4zMzPiMzMz1DMzM8UzMzPAMzMzvzMzM7EzMzOdMzMzQzMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMzSDMzM50zMzOwMzMzvjMzM8AzMzPEMzMz0zMzM+IzMzPtMzMz9TMzM/YzMzP3MzMz/DMzM/8zMzP/MzMz/zMzM/8zMzPlMzMzKTMzMwAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM1szMzP7MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM8AzMzMVMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzEDMzM7szMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/TMzM1wzMzMAMzMzAAAAAAAAAAAAMzMzADMzMwQzMzOpMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP9MzMzczMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzADMzM28zMzP6MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzOrMzMzBzMzMwAAAAAAAAAAADMzMwAzMzMvMzMz5jMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM+YzMzM9MzMzADMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzADMzMzozMzPiMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz7TMzMzkzMzMAAAAAADMzMwAzMzMAMzMzgDMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzvzMzMxozMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMxczMzO+MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzN/MzMzADMzMwAzMzMAMzMzDjMzM8IzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzOMMzMzBjMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwQzMzOMMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzyjMzMxMzMzMAMzMzADMzMzozMzPwMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz9DMzM1kzMzMAMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwAzMzNVMzMz8DMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/UzMzNDMzMzADMzMwAzMzN3MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPZMzMzLTMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMpMzMz0zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzcTMzMwAzMzMDMzMzpTMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM6gzMzMNMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMJMzMzpDMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM6ozMzMFMzMzETMzM8gzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP5MzMzZDMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMzXzMzM/YzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPQMzMzGTMzMzIzMzPnMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM9QzMzMiMzMzAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzHDMzM80zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz7jMzMzwzMzNLMzMz9TMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzejMzMwAzMzMAAAAAAAAAAAAzMzMAMzMzADMzM3gzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/czMzNTMzMzcjMzM/wzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM88zMzMXMzMzAAAAAAAAAAAAMzMzADMzMxEzMzPGMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP+MzMzczMzM54zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP0MzMzPTMzMwAAAAAAAAAAADMzMwAzMzM4MzMz8TMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM4YzMzOrMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz+TMzM0ozMzMAAAAAAAAAAAAzMzMAMzMzPzMzM/YzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzOtMzMzuTMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/UzMzM/MzMzAAAAAAAAAAAAMzMzADMzMzozMzPyMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzzDMzM9MzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPOMzMzGTMzMwAAAAAAAAAAADMzMwAzMzMSMzMzxTMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM9ozMzPaMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP0MzMzXjMzMwAzMzMAAAAAAAAAAAAzMzMAMzMzADMzM1wzMzPxMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPaMzMz2jMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPxMzMzdTMzMwYzMzMAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMEMzMzczMzM/AzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz2jMzM9ozMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPmMzMzYTMzMwQzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwMzMzNfMzMz4jMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM9szMzPaMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPeMzMzSTMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzADMzM0MzMzPaMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPaMzMz1TMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP8MzMzZDMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMzXTMzM/kzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz2jMzM7szMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz6DMzMyozMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMx8zMzPdMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM8wzMzOgMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM9UzMzMXMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMOMzMzyDMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzOWMzMzYDMzM/gzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzPFMzMzDDMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzCTMzM8AzMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP7MzMzZTMzMyAzMzPSMzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMzwDMzMwkzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwgzMzO+MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz2TMzMygzMzMAMzMzaDMzM/IzMzP/MzMz8zMzM84zMzP0MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM7wzMzMIMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMEMzMzrjMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP/MzMz/zMzM/8zMzP2MzMzzzMzM/EzMzP/MzMz8zMzM2kzMzMAMzMzADMzMwUzMzNOMzMzjTMzM00zMzMSMzMznDMzM/8zMzP/MzMz/zMzM/8zMzPoMzMz7jMzM/8zMzP/MzMz/zMzM/4zMzPgMzMz+TMzM/8zMzP/MzMz/zMzM/8zMzOoMzMzAzMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzADMzM5ozMzP/MzMz/zMzM/8zMzP/MzMz+zMzM+AzMzP9MzMz/zMzM/8zMzP/MzMz8DMzM+gzMzP/MzMz/zMzM/8zMzP/MzMzojMzMxQzMzNJMzMzjTMzM1EzMzMGMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMywzMzPWMzMz/zMzM/8zMzPcMzMzRjMzM3gzMzP7MzMz/zMzM/8zMzPlMzMzYDMzM+UzMzP/MzMz/zMzM/8zMzP/MzMzkTMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzOWMzMz/zMzM/8zMzP/MzMz/zMzM+4zMzNmMzMz3zMzM/8zMzP/MzMz/TMzM3gzMzNDMzMz2DMzM/8zMzP/MzMz3DMzMzMzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMzOTMzM5EzMzOOMzMzNjMzMwAzMzMPMzMziTMzM9szMzPkMzMzczMzMyczMzPlMzMz/zMzM/8zMzP/MzMz/zMzM3kzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzkDMzM/8zMzP/MzMz/zMzM/8zMzPuMzMzNTMzM24zMzPjMzMz3DMzM48zMzMTMzMzADMzMzMzMzOMMzMzkzMzMz0zMzMAMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwMzMzMdMzMzJTMzMwIzMzMoMzMz5zMzM/8zMzP/MzMz/zMzM/8zMzNqMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM3szMzP/MzMz/zMzM/8zMzP/MzMz8TMzMzczMzMAMzMzJTMzMx4zMzMEMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzMjMzM+4zMzP/MzMz/zMzM/8zMzP/MzMzaTMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzNlMzMz/zMzM/8zMzP/MzMz/zMzM/UzMzM9MzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMz4zMzP1MzMz/zMzM/8zMzP/MzMz/zMzM2EzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzTzMzM/ozMzP/MzMz/zMzM/8zMzP2MzMzPzMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzM/MzMz9jMzM/8zMzP/MzMz/zMzM/ozMzNMMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM0AzMzP3MzMz/zMzM/8zMzP/MzMz9zMzM0EzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzQjMzM/czMzP/MzMz/zMzM/8zMzP2MzMzQDMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzM/MzMz9jMzM/8zMzP/MzMz/zMzM/ozMzNQMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM1UzMzP8MzMz/zMzM/8zMzP/MzMz9jMzMz8zMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzOjMzM/MzMzP/MzMz/zMzM/8zMzP/MzMzZDMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzNtMzMz/zMzM/8zMzP/MzMz/zMzM/IzMzM4MzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMyozMzPoMzMz/zMzM/8zMzP/MzMz/zMzM2kzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzhzMzM/8zMzP/MzMz/zMzM/8zMzPnMzMzKDMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMbMzMz3DMzM/8zMzP/MzMz/zMzM/8zMzNvMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM5YzMzP/MzMz/zMzM/8zMzP/MzMz2jMzMxozMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzEDMzM8szMzP/MzMz/zMzM/8zMzP/MzMzhjMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzOWMzMz/zMzM/8zMzP/MzMz/zMzM8kzMzMPMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwkzMzPBMzMz/zMzM/8zMzP/MzMz/zMzM5wzMzMAMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMznjMzM/8zMzP/MzMz/zMzM/8zMzPAMzMzCTMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMJMzMzwDMzM/8zMzP/MzMz/zMzM/8zMzOwMzMzBTMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzBTMzM7IzMzP/MzMz/zMzM/8zMzP/MzMzwDMzMwkzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzBzMzM7kzMzP/MzMz/zMzM/8zMzP/MzMzvjMzMwgzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwkzMzO/MzMz/zMzM/8zMzP/MzMz/zMzM7AzMzMFMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwEzMzOhMzMz/zMzM/8zMzP/MzMz/zMzM8AzMzMJMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMJMzMzwDMzM/8zMzP/MzMz/zMzM/8zMzORMzMzADMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzljMzM/8zMzP/MzMz/zMzM/8zMzPCMzMzCjMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzCTMzM8AzMzP/MzMz/zMzM/8zMzP/MzMzcjMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzM4MzMzP/MzMz/zMzM/8zMzP/MzMzxjMzMw0zMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwkzMzPAMzMz/zMzM/8zMzP/MzMz/jMzM14zMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzNTMzMz+zMzM/8zMzP/MzMz/zMzM8UzMzMMMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMIMzMzvTMzM/8zMzP/MzMz/zMzM/MzMzM8MzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzNDMzM+4zMzP/MzMz/zMzM/8zMzPAMzMzCTMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzATMzM50zMzP/MzMz/zMzM/8zMzPMMzMzFDMzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMw0zMzPCMzMz/zMzM/8zMzP/MzMznzMzMwIzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzNKMzMz5TMzM/8zMzPyMzMzZzMzMwAzMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMwAzMzMAMzMzZzMzM/AzMzP/MzMz6TMzM0szMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMAMzMzAzMzMzMzMzNcMzMzQDMzMwczMzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzADMzMwYzMzM9MzMzXDMzMzUzMzMEMzMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////////////////////4AAH///gAAfgAAP//8AAB+AAAf//gAAHwAAB//+AAAPAAAD//wAAA8AAAH/+AAADgAAAP/wAAAGAAAA//AAAAYAAAB/4AAABAAAAD/AAAAAAAAAP8AAAAAAAAAfgAAAAAAAAB+AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAB+AAAAAAAAAH4AAAAAAAAA/wAAAAAAAAH/wAAAAAAAB//gAAAAAAAH/+AAAAAAAAf/4AAAAAAAB//gAAAAAAAH/+AAAAgAAAf/4AAAGAAAB//wAAAfwAAP//AAA//hAA//8ACH//+AD//wAf////gP//Af////+A//8B/////4D//wH/////gP//Af////+A//8B/////4D//wH/////gP//Af////+A//8B/////4D//wH/////AP//AP////8A//8A/////wD//wD/////Af//gP////8B//+A/////wH//4D/////Af//gP////8B//+A/////4P//8H/////g///wf////////////////////////////////////////////////////////////////////////////8='
b1_v=1
b2_v=1
b3_v=1
b4_v=1
b1_s=True
b2_s=False
b3_s=False
b4_s=False
bj='p1'

def gameover():
    global b1_v,b2_v,b3_v,b4_v,b1_s,b2_s,b3_s,b4_s,bj
    print(bj)
    b1_v=1
    b2_v=1
    b3_v=1
    b4_v=1
    var1.set("    %d    "%1)
    var2.set("    %d    "%1)
    var3.set("    %d    "%1)
    var4.set("    %d    "%1)
    b1_s=False
    b2_s=False
    b3_s=False
    b4_s=False
    b1.config(state='normal')
    b2.config(state='normal')
    b3.config(state='normal')
    b4.config(state='normal')
    b1.config(fg='black')
    b2.config(fg='black')
    b3.config(fg='black')
    b4.config(fg='black')
    if bj=='p1':
        b1_s=True
        b1.config(fg='red')
        msgbox.showinfo(title='GameOver', message='\n    ★player1 win    \n')
    else:
        b4_s=True
        b4.config(fg='red')
        msgbox.showinfo(title='GameOver', message='\n    ★player2 win    \n')
    return 8


def butt_1():
    global b1_v,b2_v,b3_v,b4_v,b1_s,b2_s,b3_s,b4_s,bj
    aaaa=1
    if b3_s:
        b3_v+=b1_v
        if b3_v>10:
            b3_v-=10
        elif b3_v==10:
            if b4_v!=10:
                b3.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var3.set("    %d    "%b3_v)
            b3_s=False
            b3.config(fg='black')
            b1.config(fg='black')
            b1_s=False
            bj='p1'
            var_p1.set('    ★player1    ')
            var_p2.set('    ☆player2    ')
    elif b4_s:
        b4_v+=b1_v
        if b4_v>10:
            b4_v-=10
        elif b4_v==10:
            if b3_v!=10:
                b4.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var4.set("    %d    "%b4_v)
            b4_s=False
            b4.config(fg='black')
            b1.config(fg='black')
            b1_s=False
            bj='p1'
            var_p1.set('    ★player1    ')
            var_p2.set('    ☆player2    ')
    else:
        if bj=='p1':
            if b2_s:
                b2_s=False
                b1_s=True
                b1.config(fg='red')
                b2.config(fg='black')
            elif b1_s:
                b1_s=False
                b1.config(fg='black')
            else:
                b1_s=True
                b1.config(fg='red')


def butt_2():
    global b1_v,b2_v,b3_v,b4_v,b1_s,b2_s,b3_s,b4_s,bj
    aaaa=1
    if b3_s:
        b3_v+=b2_v
        if b3_v>10:
            b3_v-=10
        elif b3_v==10:
            if b4_v!=10:
                b3.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var3.set("    %d    "%b3_v)
            b3_s=False
            b3.config(fg='black')
            b2.config(fg='black')
            b2_s=False
            bj='p1'
            var_p1.set('    ★player1    ')
            var_p2.set('    ☆player2    ')
    elif b4_s:
        b4_v+=b2_v
        if b4_v>10:
            b4_v-=10
        elif b4_v==10:
            if b3_v!=10:
                b4.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var4.set("    %d    "%b4_v)
            b4_s=False
            b4.config(fg='black')
            b2.config(fg='black')
            b2_s=False
            bj='p1'
            var_p1.set('    ★player1    ')
            var_p2.set('    ☆player2    ')
    else:
        if bj=='p1':
            if b1_s:
                b1_s=False
                b2_s=True
                b2.config(fg='red')
                b1.config(fg='black')
            elif b2_s:
                b2_s=False
                b2.config(fg='black')
            else:
                b2_s=True
                b2.config(fg='red')

def butt_3():
    global b1_v,b2_v,b3_v,b4_v,b1_s,b2_s,b3_s,b4_s,bj
    aaaa=1
    if b1_s:
        b1_v+=b3_v
        if b1_v>10:
            b1_v-=10
        elif b1_v==10:
            if b2_v!=10:
                b1.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var1.set("    %d    "%b1_v)
            b1_s=False
            b1.config(fg='black')
            b3.config(fg='black')
            b3_s=False
            bj='p2'
            var_p2.set('    ★player2    ')
            var_p1.set('    ☆player1    ')
    elif b2_s:
        b2_v+=b3_v
        if b2_v>10:
            b2_v-=10
        elif b2_v==10:
            if b1_v!=10:
                b2.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var2.set("    %d    "%b2_v)
            b2_s=False
            b2.config(fg='black')
            b3.config(fg='black')
            b3_s=False
            bj='p2'
            var_p2.set('    ★player2    ')
            var_p1.set('    ☆player1    ')
    else:
        if bj=='p2':
            if b4_s:
                b4_s=False
                b3_s=True
                b3.config(fg='red')
                b4.config(fg='black')
            elif b3_s:
                b3_s=False
                b3.config(fg='black')
            else:
                b3_s=True
                b3.config(fg='red')

def butt_4():
    global b1_v,b2_v,b3_v,b4_v,b1_s,b2_s,b3_s,b4_s,bj
    aaaa=1
    if b1_s:
        b1_v+=b4_v
        if b1_v>10:
            b1_v-=10
        elif b1_v==10:
            if b2_v!=10:
                b1.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var1.set("    %d    "%b1_v)
            b1_s=False
            b1.config(fg='black')
            b4.config(fg='black')
            b4_s=False
            bj='p2'
            var_p2.set('    ★player2    ')
            var_p1.set('    ☆player1    ')
    elif b2_s:
        b2_v+=b4_v
        if b2_v>10:
            b2_v-=10
        elif b2_v==10:
            if b1_v!=10:
                b2.config(state='disabled')
            else:
                aaaa=gameover()
        if aaaa!=8:
            var2.set("    %d    "%b2_v)
            b2_s=False
            b2.config(fg='black')
            b4.config(fg='black')
            b4_s=False
            bj='p2'
            var_p2.set('    ★player2    ')
            var_p1.set('    ☆player1    ')
    else:
        if bj=='p2':
            if b3_s:
                b3_s=False
                b4_s=True
                b4.config(fg='red')
                b3.config(fg='black')
            elif b4_s:
                b4_s=False
                b4.config(fg='black')
            else:
                b4_s=True
                b4.config(fg='red')

win = Tk()
win.title('finger-game')
win.geometry('+500+140')
win.resizable(width=False, height=False)

tmp = open("tmp.ico","wb+")
tmp.write(base64.b64decode(img))
tmp.close()
win.iconbitmap("tmp.ico")
os.remove("tmp.ico")

var1 = StringVar()
var2 = StringVar()
var3 = StringVar()
var4 = StringVar()
var_p1 = StringVar()
var_p2 = StringVar()

l0 = Label(win,text='',bg='#00aaff',font=("幼圆",5)).grid(row=0,column=0,sticky='W'+'N'+'E')

l1 = Label(win,textvariable = var_p1,fg='red',bg='#00aaff',font=("幼圆",40),height=1,width=15)
l1.grid(row=1,column=0,sticky='W'+'N'+'E')
var_p1.set('    ★player1    ')


l2 = Label(win,text='',bg='#00aaff',font=("幼圆",5)).grid(row=2,column=0,sticky='W'+'N'+'E')
root1 = Frame(win,bg='#00aaff',borderwidth=2)
j0=Label(root1,text='',bg='#00aaff',font=("幼圆",5),width=30,height=8).grid(row=0,column=0,sticky='W'+'N'+'E'+'S')

b1=Button(root1,state='normal',textvariable = var1,width=10,height=8,font=("幼圆",20,"bold"),fg='red',bg='RoyalBlue',activebackground='blue',command =butt_1)
b1.grid(row=0,column=1,sticky='W'+'N'+'E'+'S')
var1.set("    %d    "%1)
b1.config(relief=FLAT)

j1=Label(root1,text='',bg='#00aaff',font=("幼圆",5),width=40,height=8).grid(row=0,column=2,sticky='W'+'N'+'E'+'S')

b2=Button(root1,state='normal',textvariable = var2,width=10,height=8,font=("幼圆",20,"bold"),fg='black',bg='RoyalBlue',activebackground='blue',command =butt_2)
b2.grid(row=0,column=3,sticky='W'+'N'+'E'+'S')
var2.set("    %d    "%1)
b2.config(relief=FLAT)

j2=Label(root1,text='',bg='#00aaff',font=("幼圆",5),width=30,height=8).grid(row=0,column=4,sticky='W'+'N'+'E'+'S')
root1.grid(row=3,column=0,sticky='W'+'N'+'E'+'S')
l4 = Label(win,text='',bg='#00aaff',font=("幼圆",30)).grid(row=4,column=0,sticky='W'+'N'+'E')
l5 = Label(win,text='',bg='yellow',font=("幼圆",1)).grid(row=5,column=0,sticky='W'+'N'+'E')
l6 = Label(win,text='',bg='#00aaff',font=("幼圆",30)).grid(row=6,column=0,sticky='W'+'N'+'E')
root2 = Frame(win,bg='#00aaff',borderwidth=2)
j3=Label(root2,text='',bg='#00aaff',font=("幼圆",5),width=30,height=8).grid(row=0,column=0,sticky='W'+'N'+'E'+'S')

b3=Button(root2,state='normal',textvariable = var3,width=10,height=8,font=("幼圆",20,"bold"),fg='black',bg='RoyalBlue',activebackground='blue',command =butt_3)
b3.grid(row=0,column=1,sticky='W'+'N'+'E'+'S')
var3.set("    %d    "%1)
b3.config(relief=FLAT)

j4=Label(root2,text='',bg='#00aaff',font=("幼圆",5),width=40,height=8).grid(row=0,column=2,sticky='W'+'N'+'E'+'S')

b4=Button(root2,state='normal',textvariable = var4,width=10,height=8,font=("幼圆",20,"bold"),fg='black',bg='RoyalBlue',activebackground='blue',command =butt_4)
b4.grid(row=0,column=3,sticky='W'+'N'+'E'+'S')
var4.set("    %d    "%1)
b4.config(relief=FLAT)

j5=Label(root2,text='',bg='#00aaff',font=("幼圆",5),width=30,height=8).grid(row=0,column=4,sticky='W'+'N'+'E'+'S')
root2.grid(row=7,column=0,sticky='W'+'N'+'E'+'S')
l8 = Label(win,text='',bg='#00aaff',font=("幼圆",5)).grid(row=8,column=0,sticky='W'+'N'+'E')

l9 = Label(win,textvariable = var_p2,fg='blue',bg='#00aaff',font=("幼圆",40),height=1,width=15)
l9.grid(row=9,column=0,sticky='W'+'N'+'E')
var_p2.set('    ☆player2    ')

l10 = Label(win,text='',bg='#00aaff',font=("幼圆",5)).grid(row=10,column=0,sticky='W'+'N'+'E')

win.mainloop()